spring:
  datasource:
    url: jdbc:mysql://3.37.2.144:8000/bada?characterEncoding=UTF-8
    username: root
    password: 1234
#    url: jdbc:mariadb://localhost:3306/loadtest
#    username: darass
#    password: local
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 3
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  redis:
    host: 3.37.202.55
    password: password
    port: 8000
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
